import AVFoundation
import Foundation
import XCTest
@testable import MaqamStudio

/// Fixtures and scratch folders shared by the tests.
enum TestSupport {
    /// A fixture from Tests/Fixtures (generated by tools/make_fixtures.py).
    static func fixture(_ name: String, file: StaticString = #filePath, line: UInt = #line) throws -> URL {
        let bundle = Bundle(for: BundleToken.self)
        let parts = name.split(separator: ".", maxSplits: 1).map(String.init)
        guard let url = bundle.url(forResource: parts[0], withExtension: parts.count > 1 ? parts[1] : nil) else {
            XCTFail("Missing fixture \(name); run tools/make_fixtures.py", file: file, line: line)
            throw CocoaError(.fileNoSuchFile)
        }
        return url
    }

    /// A fresh empty folder, removed when the test case finishes.
    static func temporaryFolder(_ testCase: XCTestCase) throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("MaqamStudioTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        testCase.addTeardownBlock {
            makeWritable(url)
            try? FileManager.default.removeItem(at: url)
        }
        return url
    }

    /// Read-only originals would otherwise survive the cleanup.
    static func makeWritable(_ folder: URL) {
        guard let items = FileManager.default.enumerator(at: folder, includingPropertiesForKeys: nil) else { return }
        for case let item as URL in items {
            try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: item.path)
        }
    }

    /// Whole seconds, because project dates are stored as ISO 8601 without fractions.
    static let fixedDate = Date(timeIntervalSince1970: 1_790_000_000)

    /// Mono float samples of an audio file, averaged across channels.
    static func monoSamples(of url: URL) throws -> (samples: [Float], sampleRate: Double) {
        let file = try AVAudioFileBox(url: url)
        return (file.mono, file.sampleRate)
    }
}

private final class BundleToken {}

/// Reads a whole (small) file into memory for tests.
struct AVAudioFileBox {
    let mono: [Float]
    let sampleRate: Double

    init(url: URL) throws {
        let file = try AVAudioFile(forReading: url)
        let format = file.processingFormat
        guard let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(file.length)) else {
            throw CocoaError(.fileReadUnknown)
        }
        try file.read(into: buffer)
        let channels = Int(format.channelCount)
        let frames = Int(buffer.frameLength)
        var mono = [Float](repeating: 0, count: frames)
        if let data = buffer.floatChannelData {
            for channel in 0..<channels {
                for frame in 0..<frames { mono[frame] += data[channel][frame] / Float(channels) }
            }
        }
        self.mono = mono
        self.sampleRate = format.sampleRate
    }
}
